### ISSUE TITLE
Backend setup instructions in 1.12 are unclear for me

### ISSUE THREAD

**Issue by TheJacobWalters** [docker-hy/docker-hy.github.io#44]
I have the frontend running in production mode on 5000 and the backend is running on 8000. I press the button and get a cross-orgin request blocked notification in my web console. I see that in the README for the backend it suggest the following fix for this problem "FRONT_URL=<front-url> npm start". So I have tried following that fix but I think I am interpreting it wrong. I have run the following.

CMD ["FRONT_URL=<front-url>", "npm",  "start"]

CMD ["FRONT_URL=127.0.0.1", "npm",  "start"]

ENV FRONT_URL=<front-url>
CMD [  "npm", "start" ]

ENV FRONT_URL=<127.0.0.1>
CMD [  "npm", "start" ]

**Comment by Jakousa** [comment]
Best place to get help with your exercises is from the course telegram channel https://t.me/joinchat/HIg2vkuQ1T4QUPJDxIgshQ

FRONT_URL needs to be the actual url, address you'd use in your browser to access the service.  (protocol and port included) Otherwise your solutions look promising. I've changed the instructions to have "without < >". 👍

Your error should look something like this (on my chrome, no plugins):

<img width="1436" alt="Screenshot 2019-06-05 at 12 29 26" src="https://user-images.githubusercontent.com/6400208/58945993-9ca97300-878d-11e9-82af-4e0c20879caf.png">

If you match the invalid value (FRONT_URL) and origin from the image it should pass.
